services:
  music-library:
    user: root
    ports:
      - ${API_PORT}:${API_PORT}
    container_name: music-library
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - music-network

  postgres:
    user: root
    image: bitnami/postgresql:16
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:?error}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME:?error}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE:?error}
    volumes:
      - ./pg-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}'" ]
      interval: 30s
      timeout: 60s
      retries: 5
    networks:
      - music-network

networks:
  music-network:
    driver: bridge